### ISSUE TITLE
New fullscreen argument don't act as expected

### ISSUE THREAD

**Issue by sivolc73** [bluecherrydvr/unity#288]
When launching the app with the fullscreen argument I see the frame of the window go fullscreen briefly then go back to default size

Note that windows decorations are absent from the top, so the app is in fullscreen mode, just not covering the whole screen, the immersive mode do the same thing.

If I go in settings and then uncheck and recheck the fullscreen mode it will correctly toggle to a real full screen mode.

I don't know if the logs are relevant to this bug: 
```
[2024-11-19T12:45:23.240433] Running on UnityVideoPlayerFlutterInterface video playback
[2024-11-19T12:45:35.065420]Uncaught error
[2024-11-19T12:45:35.065420]Error: LateInitializationError: Field 'instance' has not been initialized.
[2024-11-19T12:45:35.065420]Stack trace: #0      writeLogToFile (package:bluecherry_client/utils/logging.dart)
<asynchronous suspension>

```
With fullscreen argument (bluecherry_client --fullscreen)
![Capture d’écran du 2024-11-19 13-07-55](https://github.com/user-attachments/assets/ed331a6f-b189-44ab-a9e6-b8f045313cf8)

Without full screen
![image](https://github.com/user-attachments/assets/37b217cf-a011-4137-a518-b7c5131fb35b)

Bluecherry version: 3.0.0-beta20 
Installation mode: deb package
System: 
- Ubuntu 22.04.5 LTS (Wayland) GNOME Shell 42.9
- Linux Mint 22 (X11) Mate 1.26.2

Thanks!

**Comment by bdlukaa** [comment]
This fix should land in the bleeding edge in a few minutes.

**Comment by sivolc73** [comment]
Well, the error from the log is gone but it does the same thing with the fullscreen argument, no error in log entry.
If of any use here the terminal output:

```
flutter: PathNotFoundException: Deletion failed, path = '/home/clovis/.local/share/com.bluecherrydvr/events.json' (OS Error: Aucun fichier ou dossier de ce nom, errno = 2)
flutter: #0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:180)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      Future._propagateToListeners.handleWhenCompleteCallback.<anonymous closure> (dart:async/future_impl.dart:854)
<asynchronous suspension>
#4      FileSystemEntityExtension.delete_ (package:safe_local_storage/file_system.dart:495)
<asynchronous suspension>
#5      SafeLocalStorage._delete (package:safe_local_storage/safe_local_storage.dart:239)
<asynchronous suspension>
#6      SafeLocalStorage.delete.<anonymous closure> (package:safe_local_storage/safe_local_storage.dart:150)
<asynchronous suspension>
#7      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:36)
<asynchronous suspension>
#8      migrate (package:bluecherry_client/utils/storage.dart:78)
<asynchronous suspension>
#9      configureStorage (package:bluecherry_client/utils/storage.dart:56)
<asynchronous suspension>
#10     main.<anonymous closure> (package:bluecherry_client/main.dart:76)
<asynchronous suspension>

flutter: The default downloads is /home/clovis/.local/share/com.bluecherrydvr/downloads
flutter: The default downloads is /home/clovis/.local/share/com.bluecherrydvr/downloads
flutter: SettingsProvider initialized
flutter: Opening app with [--fullscreen]
flutter: FINE: 2024-11-19 20:59:47.722467: registerVideoPlayerPlatformsWith: {player: {avformat.analyzeduration: 10000, avformat.probesize: 1000, avformat.fpsprobesize: 0, avformat.fflags: +nobuffer, avformat.avioflags: direct}}
flutter: INFO: 2024-11-19 20:59:47.725163: Wrote log file to "/home/clovis/.local/share/com.bluecherrydvr/logs.txt"
flutter: Running on UnityVideoPlayerFlutterInterface video playback
flutter: Checking server credentials for server Serveur Bijouterie;bluecherry.bijouteriehoule.com;7001
flutter: ServersProvider initialized
flutter: DownloadsManager initialized
flutter: MobileViewProvider initialized
flutter: ==== RECEIVED BAD CERTIFICATE FROM ********.com
flutter: ********.com:7001 with status code 200
flutter: Headers: {connection: keep-alive, cache-control: no-store, no-cache, must-revalidate, set-cookie: bluecherrydvr=ihk7nmbgnvs36ht65gnnncflnc; path=/, date: Wed, 20 Nov 2024 01:59:47 GMT, transfer-encoding: chunked, content-encoding: gzip, pragma: no-cache, content-type: text/html; charset=UTF-8, server: nginx/1.18.0 (Ubuntu), expires: Thu, 19 Nov 1981 08:52:00 GMT}
flutter: Body: {"success":true,"server_uuid":"58c04f16-dd76-11ed-81d8-7af431c410bb"}
flutter: DesktopViewProvider initialized

```
And the very short log:
```
[2024-11-19T21:01:16.088401] App working directory: /home/clovis/.local/share/com.bluecherrydvr
[2024-11-19T21:01:17.003144] Running on UnityVideoPlayerFlutterInterface video playback
```

**Comment by bdlukaa** [comment]
The app doesn't start in fullscreen?

That error is ignorable. It just says the app has been migrated to the new storage system.

**Comment by sivolc73** [comment]
I just updated my windows machine also and it is the same problem when using the fullscreen argument

I captured it for you on windows:

https://github.com/user-attachments/assets/416ea0b0-4d9a-4949-95fa-59f74db570a4
